version: '3.8'

services:
    php:
        restart: always
        container_name: ${CONTAINER_PREFIX}_php
        build:
            context: ./services/php/fpm
            args:
                PROJECT_NAME: ${PROJECT_NAME}
                GITHUB_USER: ${GITHUB_USER}
                GITHUB_TOKEN: ${GITHUB_TOKEN}
                GITHUB_EMAIL: ${GITHUB_EMAIL}
                GITHUB_NAME: ${GITHUB_NAME}
        expose:
            - '9000'
        volumes:
            - ./services/php/fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./services/php/fpm/bashrc_config.txt:/usr/local/share/bashrc_config.txt
            - ./app:/var/www/${PROJECT_NAME}
            - ./services/composer/cache:/root/.composer/cache
        environment:
            - PHP_IDE_CONFIG=serverName=${PROJECT_NAME}
            - TIMEZONE=${TIMEZONE}
            - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST}
        networks:
            - default

    nginx:
        restart: always
        container_name: ${CONTAINER_PREFIX}_nginx
        image: nginx:1.21.6-alpine
        ports:
            - '${NGINX_SSL_PORT}:443'
        env_file:
            - .env
        volumes:
            - ./services/nginx:/etc/nginx/templates
            - ./services/ssl:/etc/ssl
            - ./app:/var/www/${PROJECT_NAME}
        environment:
            - PROJECT_NAME=${PROJECT_NAME}
        networks:
            - default

    mysql:
        restart: always
        container_name: ${CONTAINER_PREFIX}_mysql
        image: mysql:8.0.28
        ports:
            - '${MYSQL_PORT}:3306'
        env_file:
            - .env
        volumes:
            - ./services/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./services/mysql/data:/var/lib/mysql
        networks:
            - default

    redis:
        restart: always
        container_name: ${CONTAINER_PREFIX}_redis
        image: redis:6.2.6-alpine
        expose:
            - '6379'
        volumes:
            - ./app:/var/www/${PROJECT_NAME}
            - ./services/redis/data:/data
            - ./services/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
        networks:
            - default

    swagger:
        restart: always
        container_name: ${CONTAINER_PREFIX}_swagger
        image: swaggerapi/swagger-ui:v4.2.1
        ports:
            - '${SWAGGER_PORT}:8080'
        volumes:
            - ./app:/var/www/${PROJECT_NAME}
        environment:
            - API_URL=${SWAGGER_API_URL}
        networks:
            - default

networks:
    default:
        external: true
        name: ${PROJECT_NAME}
