version: '3.8'

services:
    php:
        restart: unless-stopped
        container_name: ${CONTAINER_PREFIX:?must be specified}_php
        build:
            context: ./services/php/fpm
            args:
                PROJECT_NAME: ${PROJECT_NAME:?must be specified}
                GITHUB_USER: ${GITHUB_USER}
                GITHUB_TOKEN: ${GITHUB_TOKEN}
                GITHUB_EMAIL: ${GITHUB_EMAIL}
                GITHUB_NAME: ${GITHUB_NAME}
        expose:
            - '9000'
        environment:
            - PHP_IDE_CONFIG=serverName=${PROJECT_NAME:?must be specified}
            - TIMEZONE=${TIMEZONE}
            - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST}
        volumes:
            - ./services/php/fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./services/php/fpm/bashrc_config.txt:/usr/local/share/bashrc_config.txt
            - ./app:/var/www/${PROJECT_NAME:?must be specified}
            - ./services/composer/cache:/root/.composer/cache
        networks:
            - default

    nginx:
        restart: unless-stopped
        container_name: ${CONTAINER_PREFIX:?must be specified}_nginx
        image: nginx:1.21.6-alpine
        ports:
            - '${NGINX_PORT:?must be specified}:80'
            - '${NGINX_SSL_PORT:?must be specified}:443'
        environment:
            - PROJECT_NAME=${PROJECT_NAME:?must be specified}
        volumes:
            - ./services/nginx:/etc/nginx/templates
            - ./services/ssl:/etc/ssl
            - ./app:/var/www/${PROJECT_NAME:?must be specified}
        networks:
            - default

    mysql:
        restart: unless-stopped
        container_name: ${CONTAINER_PREFIX:?must be specified}_mysql
        image: mysql:8.0.28
        ports:
            - '${MYSQL_PORT:?must be specified}:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
            - MYSQL_USER=${MYSQL_USER:-dev}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:-dev}
            - MYSQL_DATABASE=${MYSQL_DATABASE:-dev}
        volumes:
            - ./services/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./services/mysql/data:/var/lib/mysql
        networks:
            - default

    redis:
        restart: unless-stopped
        container_name: ${CONTAINER_PREFIX:?must be specified}_redis
        image: redis:6.2.6-alpine
        expose:
            - '6379'
        volumes:
            - ./app:/var/www/${PROJECT_NAME:?must be specified}
            - ./services/redis/data:/data
            - ./services/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
        networks:
            - default

    swagger:
        restart: unless-stopped
        container_name: ${CONTAINER_PREFIX:?must be specified}_swagger
        image: swaggerapi/swagger-ui:v4.5.0
        ports:
            - '${SWAGGER_PORT:?must be specified}:8080'
        volumes:
            - ./app:/var/www/${PROJECT_NAME:?must be specified}
        environment:
            - API_URL=${SWAGGER_API_URL}
        networks:
            - default

networks:
    default:
        external: true
        name: ${PROJECT_NAME:?must be specified}
